inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/* # for circleci mostly
    - bin/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

# these two Layout rules make code easier to paste in IRB
Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*
    - config/**/*

Style/MixinUsage:
  Exclude:
    - bin/*

Style/HashSyntax:
  Enabled: false

# rails

# it's weird on references
# https://github.com/rubocop/rubocop-rails/issues/237
Rails/NotNullColumn:
  Enabled: false
