# sources need a class (source class)
# and attributes
# attribute types can be Integer or OrderedList
# OrderedList attributes need to have values sorted by the value (lowest to highest)

sources:
  conditions:
    class: Alerts::Sources::ConditionsSource
    attributes:
      am_min_height:
        name: AM Min Height
        type: Integer
      am_max_height:
        name: AM Max Height
        type: Integer
      am_rating:
        name: AM Rating
        type: OrderedList
        values:
          - NONE
          - FLAT
          - VERY_POOR
          - POOR
          - POOR_TO_FAIR
          - FAIR
          - FAIR_TO_GOOD
          - GOOD
          - VERY_GOOD
          - GOOD_TO_EPIC
          - EPIC
      pm_min_height:
        name: PM Min Height
        type: Integer
      pm_max_height:
        name: PM Max Height
        type: Integer
      pm_rating:
        name: PM Rating
        type: OrderedList
        values:
          - NONE
          - FLAT
          - VERY_POOR
          - POOR
          - POOR_TO_FAIR
          - FAIR
          - FAIR_TO_GOOD
          - GOOD
          - VERY_GOOD
          - GOOD_TO_EPIC
          - EPIC
  wave:
    class: Alerts::Sources::WaveSource
    attributes:
      direction:
        name: Direction
        type: Float
      height:
        name: Height
        type: Float
      period:
        name: Period
        type: Integer
