default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: surfmon_development

test:
  <<: *default
  database: surfmon_test
  password: <%= ENV["SURFMON_DATABASE_PASSWORD"] %> # only really used for CI

production:
  <<: *default
  database: surfmon_production
  username: surfmon
  password: <%= ENV["SURFMON_DATABASE_PASSWORD"] %>
